(define (or-gate a1 a2 output)
  (let ((a1-inv (make-wire))
       (a2-inv (make-wire))
       (and-out (make-wire)))
    (inverter a1 a1-inv)
    (inverter a2 a2-inv)
    (and-gate a1-inv a2-inv and-out)
    (inverter and-out output)
    'ok)
)
